Repository meilisearch/meilisearch-swift, pull requests merged in 2020-10, with the labels that each got.

#50 [#25] Remove sys-info routes
  .gitignore
  Sources/MeiliSearch/Client.swift
  Sources/MeiliSearch/Constants.swift
  Sources/MeiliSearch/Documents.swift
  Sources/MeiliSearch/Indexes.swift
  Sources/MeiliSearch/Model/PrettySystemInfo.swift
  Sources/MeiliSearch/Model/SystemInfo.swift
  Sources/MeiliSearch/Search.swift
  Sources/MeiliSearch/Stats.swift
  Sources/MeiliSearch/System.swift
  Sources/MeiliSearch/Updates.swift
  Tests/MeiliSearchTests/DocumentsTests.swift
  Tests/MeiliSearchTests/IndexesTests.swift
  Tests/MeiliSearchTests/SearchTests.swift
  Tests/MeiliSearchTests/StatsTests.swift
  Tests/MeiliSearchTests/SystemTests.swift
  Tests/MeiliSearchTests/UpdatesTests.swift
Labels: Hacktoberfest

#51 [#48] Remove acceptNewFields routes
  Sources/MeiliSearch/Client.swift
  Sources/MeiliSearch/Indexes.swift
  Sources/MeiliSearch/Model/Setting.swift
  Sources/MeiliSearch/Settings.swift
  Sources/MeiliSearch/Stats.swift
  Sources/MeiliSearch/System.swift
  Sources/MeiliSearch/Updates.swift
  Tests/MeiliSearchUnitTests/IndexesTests.swift
  Tests/MeiliSearchUnitTests/SearchTests.swift
  Tests/MeiliSearchUnitTests/SettingsTests.swift
  Tests/MeiliSearchUnitTests/StatsTests.swift
  Tests/MeiliSearchUnitTests/SystemTests.swift
  Tests/MeiliSearchUnitTests/UpdatesTests.swift
Labels: Hacktoberfest

#59 Add bors config
  .github/workflows/swift-test.yml
  bors.toml
Labels: Hacktoberfest, skip-changelog

#30 Change search method from get to post
  Sources/MeiliSearch/Model/SearchParameters.swift
  Sources/MeiliSearch/Search.swift
Labels: Hacktoberfest, breaking-change

#60 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Hacktoberfest, skip-changelog

#61 Update swift-test.yml
  .github/workflows/swift-test.yml
Labels: skip-changelog

#64 Make the tests easier to read and maintain
  Sources/MeiliSearch/Model/Setting.swift
  Tests/MeiliSearchIntegrationTests/SettingsTests.swift
  Tests/MeiliSearchUnitTests/SettingsTests.swift
Labels: skip-changelog

#54 Create integrations tests for all MeiliSearch http routes
  Sources/MeiliSearch/Client.swift
  Sources/MeiliSearch/Constants.swift
  Sources/MeiliSearch/Documents.swift
  Sources/MeiliSearch/Indexes.swift
  Sources/MeiliSearch/Model/Key.swift
  Sources/MeiliSearch/Model/SearchParameters.swift
  Sources/MeiliSearch/Model/SearchResult.swift
  Sources/MeiliSearch/Model/Setting.swift
  Sources/MeiliSearch/Model/Update.swift
  Sources/MeiliSearch/Search.swift
  Sources/MeiliSearch/Settings.swift
  Sources/MeiliSearch/Stats.swift
  Sources/MeiliSearch/System.swift
  Sources/MeiliSearch/Updates.swift
  Tests/MeiliSearchIntegrationTests/DocumentsTests.swift
  Tests/MeiliSearchIntegrationTests/IndexesTests.swift
  Tests/MeiliSearchIntegrationTests/Pooling.swift
  Tests/MeiliSearchIntegrationTests/SearchTests.swift
  Tests/MeiliSearchIntegrationTests/SettingsTests.swift
  Tests/MeiliSearchIntegrationTests/UpdatesTests.swift
  Tests/MeiliSearchIntegrationTests/XCTestManifests.swift
  Tests/MeiliSearchUnitTests/SearchTests.swift
  Tests/MeiliSearchUnitTests/SettingsTests.swift
Labels: Hacktoberfest, enhancement

#67 Remove the custom SearchResult decoder
  Sources/MeiliSearch/Model/SearchResult.swift
Labels: skip-changelog

#52 Overload function 'getDocument' to accept identifier as Int too
  Sources/MeiliSearch/Client.swift
  Tests/MeiliSearchIntegrationTests/DocumentsTests.swift
Labels: Hacktoberfest

#66 Make all the search parameters optional
  Sources/MeiliSearch/Model/SearchParameters.swift
  Sources/MeiliSearch/Model/SearchResult.swift
  Tests/MeiliSearchIntegrationTests/SearchTests.swift
Labels: breaking-change

#70 Move run-tests.sh to a distinct folder
  CONTRIBUTING.md
  Scripts/run-test.sh
Labels: Hacktoberfest, enhancement, skip-changelog

#53 Add support to Encodable types for addDocuments function
  Sources/MeiliSearch/Client.swift
  Sources/MeiliSearch/Constants.swift
  Sources/MeiliSearch/Documents.swift
  Tests/MeiliSearchIntegrationTests/DocumentsTests.swift
  Tests/MeiliSearchUnitTests/ClientTests.swift
  Tests/MeiliSearchUnitTests/DocumentsTests.swift
Labels: Hacktoberfest, enhancement

#71 Change the update status as enum and rename Type into UpdateType in Update model
  Sources/MeiliSearch/Model/Update.swift
  Tests/MeiliSearchIntegrationTests/DocumentsTests.swift
  Tests/MeiliSearchIntegrationTests/SettingsTests.swift
  Tests/MeiliSearchIntegrationTests/UpdatesTests.swift
  Tests/MeiliSearchUnitTests/UpdatesTests.swift
Labels: Hacktoberfest, breaking-change, enhancement

#82 [#77] Add SwiftLint job for test workflow
  .github/workflows/swift-doc.yml
  .github/workflows/swift-test.yml
  .swiftlint.yml
  Scripts/swiftlint.sh
Labels: Hacktoberfest, enhancement

#84 Fix CI
  .github/workflows/swift-test.yml
Labels: skip-changelog

#72 Add dump support
  Sources/MeiliSearch/Client.swift
  Sources/MeiliSearch/Dumps.swift
  Sources/MeiliSearch/Model/Dump.swift
  Tests/MeiliSearchIntegrationTests/DocumentsTests.swift
  Tests/MeiliSearchIntegrationTests/DumpsTests.swift
  Tests/MeiliSearchIntegrationTests/SearchTests.swift
  Tests/MeiliSearchIntegrationTests/SettingsTests.swift
  Tests/MeiliSearchIntegrationTests/UpdatesTests.swift
  Tests/MeiliSearchIntegrationTests/XCTestManifests.swift
  Tests/MeiliSearchUnitTests/DumpsTests.swift
  Tests/MeiliSearchUnitTests/XCTestManifests.swift
Labels: Hacktoberfest, enhancement

#73 Addd waitForPending update method
  Sources/MeiliSearch/Model/Update.swift
  Sources/MeiliSearch/Updates.swift
  Tests/MeiliSearchIntegrationTests/DocumentsTests.swift
  Tests/MeiliSearchIntegrationTests/Pooling.swift
  Tests/MeiliSearchIntegrationTests/SearchTests.swift
  Tests/MeiliSearchIntegrationTests/SettingsTests.swift
  Tests/MeiliSearchIntegrationTests/UpdatesTests.swift
Labels: Hacktoberfest, enhancement

#83 Fix docs CI
  .github/workflows/swift-docs.yml
Labels: skip-changelog

#86 Add bors badge
  README.md
Labels: enhancement, skip-changelog

#89 Update dump status
  Sources/MeiliSearch/Client.swift
  Sources/MeiliSearch/Model/Dump.swift
  Tests/MeiliSearchUnitTests/DumpsTests.swift
Labels: breaking-change

#90 Remove the udpateHealth method
  .code-samples.meilisearch.yaml
  Sources/MeiliSearch/Client.swift
  Sources/MeiliSearch/System.swift
  Tests/MeiliSearchUnitTests/SystemTests.swift
Labels: breaking-change

#85 Fix demos
  Demos/PerfectDemo/Package.swift
  Demos/PerfectDemo/Sources/PerfectTemplate/main.swift
  Demos/VaporDemo/Package.swift
  Demos/VaporDemo/Sources/App/routes.swift
  README.md
Labels: bug, skip-changelog
