Repository meilisearch/meilisearch-swift, pull requests merged in 2021-07, with the labels that each got.

#150 Add SwiftLint for demos and tests
  .swiftlint.yml
  Demos/PerfectDemo/Sources/PerfectTemplate/main.swift
  Demos/VaporDemo/Sources/App/routes.swift
  Sources/MeiliSearch/Client.swift
  Tests/MeiliSearchIntegrationTests/DocumentsTests.swift
  Tests/MeiliSearchIntegrationTests/DumpsTests.swift
  Tests/MeiliSearchIntegrationTests/IndexesTests.swift
  Tests/MeiliSearchIntegrationTests/Pooling.swift
  Tests/MeiliSearchIntegrationTests/SearchTests.swift
  Tests/MeiliSearchIntegrationTests/SettingsTests.swift
  Tests/MeiliSearchIntegrationTests/UpdatesTests.swift
  Tests/MeiliSearchIntegrationTests/XCTestManifests.swift
  Tests/MeiliSearchUnitTests/ClientTests.swift
  Tests/MeiliSearchUnitTests/DocumentsTests.swift
  Tests/MeiliSearchUnitTests/DumpsTests.swift
  Tests/MeiliSearchUnitTests/IndexesTests.swift
  Tests/MeiliSearchUnitTests/KeysTests.swift
  Tests/MeiliSearchUnitTests/MockURLSession.swift
  Tests/MeiliSearchUnitTests/SearchTests.swift
  Tests/MeiliSearchUnitTests/SettingsTests.swift
  Tests/MeiliSearchUnitTests/StatsTests.swift
  Tests/MeiliSearchUnitTests/SystemTests.swift
  Tests/MeiliSearchUnitTests/UpdatesTests.swift
  Tests/MeiliSearchUnitTests/XCTestManifests.swift
Labels: enhancement

#156 Make linting CI tests strict
  .swiftlint.yml
  Demos/VaporDemo/Package.swift
  Demos/VaporDemo/Sources/App/configure.swift
  Demos/VaporDemo/Sources/App/routes.swift
  Demos/VaporDemo/Tests/AppTests/AppTests.swift
  Scripts/swiftlint.sh
  Tests/MeiliSearchIntegrationTests/IndexesTests.swift
  Tests/MeiliSearchIntegrationTests/SearchTests.swift
  Tests/MeiliSearchUnitTests/DocumentsTests.swift
  Tests/MeiliSearchUnitTests/DumpsTests.swift
  Tests/MeiliSearchUnitTests/IndexesTests.swift
  Tests/MeiliSearchUnitTests/KeysTests.swift
  Tests/MeiliSearchUnitTests/SearchTests.swift
  Tests/MeiliSearchUnitTests/SettingsTests.swift
  Tests/MeiliSearchUnitTests/StatsTests.swift
  Tests/MeiliSearchUnitTests/SystemTests.swift
  Tests/MeiliSearchUnitTests/UpdatesTests.swift
Labels: skip-changelog

#145 Add Error Handler
  Sources/MeiliSearch/Error.swift
  Sources/MeiliSearch/Indexes.swift
  Sources/MeiliSearch/Request.swift
  Tests/MeiliSearchIntegrationTests/DocumentsTests.swift
  Tests/MeiliSearchIntegrationTests/DumpsTests.swift
  Tests/MeiliSearchIntegrationTests/IndexesTests.swift
  Tests/MeiliSearchIntegrationTests/Pooling.swift
  Tests/MeiliSearchIntegrationTests/SearchTests.swift
  Tests/MeiliSearchIntegrationTests/SettingsTests.swift
  Tests/MeiliSearchIntegrationTests/UpdatesTests.swift
  Tests/MeiliSearchIntegrationTests/Utils.swift
  Tests/MeiliSearchUnitTests/IndexesTests.swift
Labels: skip-changelog

#159 Change hostURL to host
  .code-samples.meilisearch.yaml
  Demos/PerfectDemo/Sources/PerfectTemplate/main.swift
  Demos/VaporDemo/Sources/App/routes.swift
  README.md
  Sources/MeiliSearch/Client.swift
  Sources/MeiliSearch/Config.swift
  Tests/MeiliSearchIntegrationTests/DocumentsTests.swift
  Tests/MeiliSearchIntegrationTests/DumpsTests.swift
  Tests/MeiliSearchIntegrationTests/IndexesTests.swift
  Tests/MeiliSearchIntegrationTests/SearchTests.swift
  Tests/MeiliSearchIntegrationTests/SettingsTests.swift
  Tests/MeiliSearchIntegrationTests/UpdatesTests.swift
  Tests/MeiliSearchUnitTests/ClientTests.swift
  Tests/MeiliSearchUnitTests/DocumentsTests.swift
  Tests/MeiliSearchUnitTests/DumpsTests.swift
  Tests/MeiliSearchUnitTests/IndexesTests.swift
  Tests/MeiliSearchUnitTests/KeysTests.swift
  Tests/MeiliSearchUnitTests/SearchTests.swift
  Tests/MeiliSearchUnitTests/SettingsTests.swift
  Tests/MeiliSearchUnitTests/StatsTests.swift
  Tests/MeiliSearchUnitTests/SystemTests.swift
  Tests/MeiliSearchUnitTests/UpdatesTests.swift
Labels: breaking-change

#161 Update the README
  README.md
Labels: skip-changelog
