Repository meilisearch/meilisearch-swift, pull requests merged in 2022-05, with the labels that each got.

#294 Update version for the next release (v0.14.0)
  .code-samples.meilisearch.yaml
  README.md
  Sources/MeiliSearch/Model/PackageVersion.swift
Labels: skip-changelog

#297 Remove all related to the generateTenantToken method
  .code-samples.meilisearch.yaml
  Package.swift
  Sources/MeiliSearch/Client.swift
  Sources/MeiliSearch/Model/SearchRules.swift
  Sources/MeiliSearch/Model/SearchRulesGroup.swift
  Sources/MeiliSearch/Model/TokenPayload.swift
  Sources/MeiliSearch/TenantTokenClaims/ApiKeyPrefixClaim.swift
  Sources/MeiliSearch/TenantTokenClaims/SearchRulesClaim.swift
  Sources/MeiliSearch/TenantTokens.swift
  Tests/MeiliSearchIntegrationTests/TenantTokensTests.swift
  Tests/MeiliSearchUnitTests/Model/SearchRulesTests.swift
  Tests/MeiliSearchUnitTests/TenantTokensTests.swift
Labels: bug

#299 Revert version from 0.14 to 0.13
  .code-samples.meilisearch.yaml
  README.md
  Sources/MeiliSearch/Model/PackageVersion.swift
Labels: maintenance

#300 Update version for the next release (v0.13.1)
  .code-samples.meilisearch.yaml
  README.md
  Sources/MeiliSearch/Model/PackageVersion.swift
Labels: skip-changelog

#291 Update version for the next release (v0.13.2)
  .code-samples.meilisearch.yaml
  README.md
  Sources/MeiliSearch/Model/PackageVersion.swift
Labels: skip-changelog

#283 Refactor the request function to use a simple request builder
  Sources/MeiliSearch/Request.swift
Labels: enhancement
