Repository meilisearch/meilisearch-swift, pull requests merged in 2022-04, with the labels that each got.

#274 DRY up the shared models between tests
  Tests/MeiliSearchIntegrationTests/DocumentsTests.swift
  Tests/MeiliSearchIntegrationTests/KeysTests.swift
  Tests/MeiliSearchIntegrationTests/SearchTests.swift
  Tests/MeiliSearchIntegrationTests/Support/Book.swift
  Tests/MeiliSearchIntegrationTests/Support/Movie.swift
  Tests/MeiliSearchIntegrationTests/TaskTests.swift
  Tests/MeiliSearchIntegrationTests/Utils.swift
Labels: enhancement

#276 Feature/Add Qualified version
  .github/scripts/check-release.sh
  .github/workflows/cocoapods.yml
  CONTRIBUTING.md
  MeiliSearch.podspec
  Sources/MeiliSearch/Model/PackageVersion.swift
  Tests/MeiliSearchUnitTests/PackageVersionTests.swift
Labels: enhancement

#277 Feature/Analytics
  Sources/MeiliSearch/Request.swift
  Tests/MeiliSearchUnitTests/ClientTests.swift
  Tests/MeiliSearchUnitTests/MockURLSession.swift
Labels: enhancement

#273 Feature/Tenant Token: Add a module which can generate tenant tokens
  .code-samples.meilisearch.yaml
  Package.swift
  Sources/MeiliSearch/Client.swift
  Sources/MeiliSearch/Model/SearchRules.swift
  Sources/MeiliSearch/Model/SearchRulesGroup.swift
  Sources/MeiliSearch/Model/TokenPayload.swift
  Sources/MeiliSearch/TenantTokenClaims/ApiKeyPrefixClaim.swift
  Sources/MeiliSearch/TenantTokenClaims/SearchRulesClaim.swift
  Sources/MeiliSearch/TenantTokens.swift
  Tests/MeiliSearchIntegrationTests/TenantTokensTests.swift
  Tests/MeiliSearchUnitTests/Model/SearchRulesTests.swift
  Tests/MeiliSearchUnitTests/TenantTokensTests.swift
Labels: enhancement, breaking-change

#278 Update code samples
  .code-samples.meilisearch.yaml
Labels: skip-changelog

#284 Add missing curly braces in landing code sample
  .code-samples.meilisearch.yaml
Labels: skip-changelog

#285 Fix tests dependent on a specific return order for the documents
  Tests/MeiliSearchIntegrationTests/DocumentsTests.swift
  Tests/MeiliSearchIntegrationTests/SearchTests.swift
Labels: skip-changelog
