Repository meilisearch/meilisearch-swift, pull requests merged in 2023-03, with the labels that each got.

#364 Fix tests with v0.30 Meilisearch
  Sources/MeiliSearch/QueryParameters/TasksQuery.swift
  Sources/MeiliSearch/Tasks.swift
  Tests/MeiliSearchIntegrationTests/SearchTests.swift
  Tests/MeiliSearchUnitTests/IndexesTests.swift
  Tests/MeiliSearchUnitTests/QueryParameters/TasksQueryTests.swift
Labels: breaking-change

#365 Update tasks parameters
  Sources/MeiliSearch/Formatter.swift
  Sources/MeiliSearch/QueryParameters/IndexesQuery.swift
  Sources/MeiliSearch/QueryParameters/KeysQuery.swift
  Sources/MeiliSearch/QueryParameters/TasksQuery.swift
  Tests/MeiliSearchIntegrationTests/TaskTests.swift
  Tests/MeiliSearchUnitTests/FormatterTests.swift
  Tests/MeiliSearchUnitTests/IndexesTests.swift
  Tests/MeiliSearchUnitTests/QueryParameters/TasksQueryTests.swift
  Tests/MeiliSearchUnitTests/TasksTests.swift
Labels: breaking-change

#369 Add finite pagination support
  .code-samples.meilisearch.yaml
  .swiftlint.yml
  Sources/MeiliSearch/Formatter.swift
  Sources/MeiliSearch/Indexes.swift
  Sources/MeiliSearch/Model/SearchParameters.swift
  Sources/MeiliSearch/Model/SearchResult.swift
  Sources/MeiliSearch/Request.swift
  Sources/MeiliSearch/Search.swift
  Tests/.swiftlint_for_tests.yml
  Tests/MeiliSearchIntegrationTests/SearchTests.swift
  Tests/MeiliSearchUnitTests/QueryParameters/TasksQueryTests.swift
  Tests/MeiliSearchUnitTests/SearchTests.swift
Labels: enhancement, breaking-change

#358 Improve the check-release tag parser to be more robust
  .github/scripts/check-release.sh
Labels: skip-changelog

#372 Add a straightforward guide about the auth for cocoapods
  CONTRIBUTING.md
Labels: documentation
