Repository meilisearch/meilisearch-swift, pull requests merged in 2023-09, with the labels that each got.

#408 Update code samples for April 2023
  .code-samples.meilisearch.yaml
Labels: skip-changelog

#409 Fill missing code samples
  .code-samples.meilisearch.yaml
Labels: skip-changelog

#414 Add support for `attributesToSearchOn` in search API
  .code-samples.meilisearch.yaml
  Sources/MeiliSearch/Model/SearchParameters.swift
  Tests/MeiliSearchIntegrationTests/SearchTests.swift
Labels: enhancement

#415 Add support for facetStats in search response
  Sources/MeiliSearch/Model/FacetStats.swift
  Sources/MeiliSearch/Model/SearchResult.swift
  Tests/MeiliSearchIntegrationTests/SearchTests.swift
Labels: enhancement

#413 Add support for search ranking score
  .code-samples.meilisearch.yaml
  Sources/MeiliSearch/Model/SearchParameters.swift
  Sources/MeiliSearch/Model/SearchResult.swift
  Tests/MeiliSearchIntegrationTests/SearchTests.swift
Labels: enhancement, breaking-change

#410 Add async overload for search API
  README.md
  Sources/MeiliSearch/Async/Indexes+async.swift
  Sources/MeiliSearch/Indexes.swift
  Tests/MeiliSearchUnitTests/SearchTests.swift
Labels: enhancement
